import type { RecentlySearchedTileProps } from "./recently-searched-tile";

const fakeData: RecentlySearchedTileProps[] = [
	{
		id: "1",
		title: "Mozart",
		type: "artist",
		imageUrl: "https://i.pravatar.cc/150?img=1",
	},
	{
		id: "2",
		title: "The Dark Side of the Moon",
		type: "album",
		imageUrl: "https://i.pravatar.cc/150?img=2",
		subtitle: "Pink Floyd",
	},
	{
		id: "3",
		title: "Bohemian Rhapsody",
		type: "track",
		imageUrl: "https://i.pravatar.cc/150?img=3",
		subtitle: "Queen",
	},
	{
		id: "4",
		title: "Adele",
		type: "artist",
		imageUrl: "https://i.pravatar.cc/150?img=4",
	},
	{
		id: "5",
		title: "Thriller",
		type: "album",
		imageUrl: "https://i.pravatar.cc/150?img=5",
		subtitle: "Michael Jackson",
	},
	{
		id: "6",
		title: "Blinding Lights",
		type: "track",
		imageUrl: "https://i.pravatar.cc/150?img=6",
		subtitle: "The Weeknd",
	},
	{
		id: "7",
		title: "Billie Eilish",
		type: "artist",
		imageUrl: "https://i.pravatar.cc/150?img=7",
	},
	{
		id: "8",
		title: "Rumours",
		type: "album",
		imageUrl: "https://i.pravatar.cc/150?img=8",
		subtitle: "Fleetwood Mac",
	},
	{
		id: "9",
		title: "Shape of You",
		type: "track",
		imageUrl: "https://i.pravatar.cc/150?img=9",
		subtitle: "Ed Sheeran",
	},
	{
		id: "10",
		title: "Beyoncé",
		type: "artist",
		imageUrl: "https://i.pravatar.cc/150?img=10",
	},
	{
		id: "11",
		title: "Back in Black",
		type: "album",
		imageUrl: "https://i.pravatar.cc/150?img=11",
		subtitle: "AC/DC",
	},
	{
		id: "12",
		title: "Dance Monkey",
		type: "track",
		imageUrl: "https://i.pravatar.cc/150?img=12",
		subtitle: "Tones and I",
	},
	{
		id: "13",
		title: "The Weeknd",
		type: "artist",
		imageUrl: "https://i.pravatar.cc/150?img=13",
	},
	{
		id: "14",
		title: "Abbey Road",
		type: "album",
		imageUrl: "https://i.pravatar.cc/150?img=14",
		subtitle: "The Beatles",
	},
	{
		id: "15",
		title: "Watermelon Sugar",
		type: "track",
		imageUrl: "https://i.pravatar.cc/150?img=15",
		subtitle: "Harry Styles",
	},
	{
		id: "16",
		title: "Dua Lipa",
		type: "artist",
		imageUrl: "https://i.pravatar.cc/150?img=16",
	},
	{
		id: "17",
		title: "After Hours",
		type: "album",
		imageUrl: "https://i.pravatar.cc/150?img=17",
		subtitle: "The Weeknd",
	},
	{
		id: "18",
		title: "Levitating",
		type: "track",
		imageUrl: "https://i.pravatar.cc/150?img=18",
		subtitle: "Dua Lipa ft. DaBaby",
	},
	{
		id: "19",
		title: "Coldplay",
		type: "artist",
		imageUrl: "https://i.pravatar.cc/150?img=19",
	},
	{
		id: "20",
		title: "Fine Line",
		type: "album",
		imageUrl: "https://i.pravatar.cc/150?img=20",
		subtitle: "Harry Styles",
	},
];

export default fakeData;
